### ISSUE TITLE
Dataset causes runtime error

### ISSUE THREAD

**Issue by ratorx** [julvo/htmlgo#2]
Dataset causes a runtime error when used multiple times in a single []a.Attribute.

I think you've already potentially already fixed this with be1ed437c8499befaa0bccd3bb7a168e15861251, but it's not propagated to the generated library (since there are some additions to dataset in the generator that aren't in the generated version).

**Comment by julvo** [comment]
Hi @ratorx, thanks for reporting this and also for spotting the problem in the generated files. Apologies for the slow reply - just regenerated the files and updated the master branch. If it's still not working for you, feel free to comment here and I'll reopen this.
